tp_fan /proc/acpi/ibm/fan

tp_thermal /proc/acpi/ibm/thermal


{ "level 0"   # the fan level
# ^-------^   This works for /proc/acpi/ibm/thermal.
#             for a PWM fan in /sys/class/hwmon it would have to be just
#             0 or "0".
#
#    Sensor count:
#    1  2  3  4  5  6  7  8  9  10 11 12 13 14 15 16
#    ==============================================
    (0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0)      # LOWER limit
    (50	.  .  .  .  .  .  .  .  .  .  .  .  .  .  .)      # UPPER limit
}


{ "level 1"
# ^-------^ For a PWM fan you may have to use something around 30 to get the
# same speed.
    (50 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (55 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level 2"
    (55 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (60 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level 3"
    (60 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (65 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level 4"
    (65 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (70 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level 5"
    (70 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (75 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level 6"
    (75 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (80 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level 7"
    (80 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (85 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}

{ "level disengaged" # nice idea: "level auto" can also be used.
                     # but again: only numbers for sysfs.
    (85 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
    (99 .  .  .  .  .  .  .  .  .  .  .  .  .  .  .)
}
